<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>amiga_local_planner</name>
  <version>0.0.1</version>
  <description>TEB local planner with 3D LiDAR costmap for Amiga robot</description>
  <maintainer email="todo@todo.com">wuyi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>nav2_costmap_2d</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_controller</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
